# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=128, verbose_name='回传state')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
            options={
                'verbose_name_plural': '验证日志',
                'verbose_name': '验证日志',
                'db_table': 'wxauth_authlog',
            },
        ),
        migrations.CreateModel(
            name='RequestTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='目标URL')),
                ('key', models.CharField(max_length=8, unique=True, verbose_name='目标')),
            ],
            options={
                'verbose_name_plural': '请求目标',
                'verbose_name': '请求目标',
                'db_table': 'wxauth_request_target',
            },
        ),
        migrations.CreateModel(
            name='ResultTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, verbose_name='令牌值')),
                ('expires', models.IntegerField(verbose_name='超时时间')),
            ],
            options={
                'verbose_name': '结果令牌',
            },
        ),
        migrations.CreateModel(
            name='WechatDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='可以填写公众号的显示名称', max_length=150, verbose_name='标题')),
                ('domain', models.CharField(help_text='公众号 > 开发 > 接口权限 > 网页授权获取用户基本信息', max_length=150, unique=True, verbose_name='域名')),
                ('app_id', models.CharField(max_length=50, unique=True, verbose_name='公众号 APP_ID')),
                ('app_secret', models.CharField(max_length=50, verbose_name='公众号 APP_SECRET')),
            ],
            options={
                'verbose_name_plural': '公众号域',
                'verbose_name': '公众号域',
                'db_table': 'wxauth_wechat_domain',
            },
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='用户OpenID')),
                ('nickname', models.CharField(max_length=128, null=True, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('province', models.CharField(max_length=120, null=True, verbose_name='省份')),
                ('city', models.CharField(max_length=120, null=True, verbose_name='城市')),
                ('country', models.CharField(max_length=120, null=True, verbose_name='国家')),
                ('headimgurl', models.URLField(null=True, verbose_name='用户头像')),
                ('avatar', models.ImageField(null=True, upload_to='avatar', verbose_name='头像文件')),
                ('privilege', models.TextField(null=True, verbose_name='用户特权信息')),
                ('unionid', models.CharField(max_length=64, null=True, verbose_name='用户unionid')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.WechatDomain', verbose_name='公众号域')),
            ],
            options={
                'ordering': ['-date_updated', '-pk'],
                'verbose_name_plural': '微信用户',
                'verbose_name': '微信用户',
                'db_table': 'wxauth_wechat_user',
            },
        ),
        migrations.AddField(
            model_name='resultticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.WechatUser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='authlog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.RequestTarget', verbose_name='目标'),
        ),
    ]
