# Generated by Django 2.2.1 on 2019-06-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='是否关注'),
        ),
    ]
