# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160920_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='可以填写公众号的显示名称', max_length=150, verbose_name='标题')),
                ('app_id', models.CharField(max_length=50, unique=True, verbose_name='APP_ID')),
                ('app_secret', models.CharField(max_length=50, verbose_name='APP_SECRET')),
                ('mch_id', models.CharField(max_length=50, verbose_name='商户号 MCH ID')),
                ('api_key', models.CharField(max_length=50, verbose_name='API 密钥')),
                ('apiclient_cert', models.TextField(verbose_name='PEM 支付证书')),
                ('apiclient_key', models.TextField(verbose_name='PEM 支付私钥')),
                ('notify_url', models.URLField(blank=True, verbose_name='异步回调URL')),
                ('trade_type', models.CharField(choices=[('JSAPI', '公众号JSAPI'), ('NATIVE', '扫码支付'), ('APP', 'APP支付'), ('WAP', '网页WAP')], max_length=20, verbose_name='支付方式')),
            ],
            options={
                'verbose_name': '微信APP',
                'db_table': 'wxauth_wechat_app',
                'verbose_name_plural': '微信APP',
            },
        ),
    ]
