# Generated by Django 2.2.1 on 2019-06-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190513_1153'),
        ('core', '0002_wechatuser_subscribe'),
    ]

    operations = [
    ]
