# Generated by Django 2.2.1 on 2019-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20190613_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='template_send_token',
            field=models.CharField(blank=True, help_text='调用 template/<appid>/send 的时候要加上 token=?? 推送', max_length=32, verbose_name='模板推送令牌'),
        ),
    ]
