# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wechatdomain_verify_key'),
        ('core', '0003_wechatapp'),
    ]

    operations = [
    ]
