# Generated by Django 2.2.1 on 2020-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200304_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatredpack',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='发放金额'),
        ),
    ]
