# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170205_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='type',
            field=models.CharField(choices=[('APP', '移动应用'), ('NATIVE', '网站应用'), ('BIZ', '公众账号')], default='APP', help_text='参照 http://open.weixin.qq.com 管理中心的应用类型', max_length=20, verbose_name='开放平台类型'),
            preserve_default=False,
        ),
    ]
