# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_paypalapp_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipayapp',
            name='oauth_redirect_url',
            field=models.URLField(blank=True, default='', verbose_name='OAuth 认证跳转地址'),
        ),
        migrations.AddField(
            model_name='alipaymapiapp',
            name='oauth_redirect_url',
            field=models.URLField(blank=True, default='', verbose_name='OAuth 认证跳转地址'),
        ),
        migrations.AddField(
            model_name='paypalapp',
            name='oauth_redirect_url',
            field=models.URLField(blank=True, default='', verbose_name='OAuth 认证跳转地址'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='oauth_redirect_url',
            field=models.URLField(blank=True, default='', verbose_name='OAuth 认证跳转地址'),
        ),
    ]
