# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170314_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalStandardApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='可以填写公众号的显示名称', max_length=150, verbose_name='标题')),
                ('app_id', models.CharField(max_length=176, unique=True, verbose_name='APP_ID')),
                ('app_secret', models.CharField(blank=True, max_length=255, verbose_name='APP_SECRET')),
                ('notify_url', models.URLField(blank=True, default='', verbose_name='授权回调地址')),
                ('return_url', models.URLField(blank=True, default='', verbose_name='授权跳转地址')),
                ('cancel_url', models.URLField(blank=True, default='', verbose_name='取消操作返回 URL')),
                ('oauth_redirect_url', models.URLField(blank=True, default='', help_text='如果是，请务必将本地址设定为本 API 的 index，例如 http://wx.easecloud.cn并且在对应的平台中注册此地址，不填的话默认会使用当前地址', verbose_name='OAuth 认证跳转地址')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='是否沙盒测试环境')),
            ],
            options={
                'db_table': 'wxauth_paypal_standard_app',
                'verbose_name': 'PayPal Standard APP',
                'verbose_name_plural': 'PayPal Standard APP',
            },
        ),
        migrations.AddField(
            model_name='alipayapp',
            name='cancel_url',
            field=models.URLField(blank=True, default='', verbose_name='取消操作返回 URL'),
        ),
        migrations.AddField(
            model_name='alipaymapiapp',
            name='cancel_url',
            field=models.URLField(blank=True, default='', verbose_name='取消操作返回 URL'),
        ),
        migrations.AddField(
            model_name='paypalapp',
            name='cancel_url',
            field=models.URLField(blank=True, default='', verbose_name='取消操作返回 URL'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='cancel_url',
            field=models.URLField(blank=True, default='', verbose_name='取消操作返回 URL'),
        ),
    ]
