# Generated by Django 2.0.5 on 2018-06-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_wechatapp_withdraw_app'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CmbPayApp',
        ),
        migrations.DeleteModel(
            name='PaypalApp',
        ),
        migrations.DeleteModel(
            name='PayPalStandardApp',
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='withdraw_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wxapp', to='core.WechatApp', verbose_name='提现关联公众号'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.WechatApp', verbose_name='微信APP'),
        ),
        migrations.AlterField(
            model_name='wechatwithdrawticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_tickets', to='core.WechatUser', verbose_name='提现用户'),
        ),
    ]
