# Generated by Django 2.0.5 on 2018-06-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180614_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authlog',
            name='target',
        ),
        migrations.DeleteModel(
            name='AuthLog',
        ),
        migrations.DeleteModel(
            name='RequestTarget',
        ),
    ]
