# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-20 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatdomain',
            name='domain',
            field=models.CharField(help_text='公众号 > 开发 > 接口权限 > 网页授权获取用户基本信息', max_length=100, unique=True, verbose_name='域名'),
        ),
    ]
