# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='city',
            field=models.CharField(max_length=120, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='country',
            field=models.CharField(max_length=120, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='headimgurl',
            field=models.URLField(null=True, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='nickname',
            field=models.CharField(max_length=128, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='privilege',
            field=models.TextField(null=True, verbose_name='用户特权信息'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='province',
            field=models.CharField(max_length=120, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='sex',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
