# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0003_auto_20160525_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlog',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wxauth_router.RequestTarget', verbose_name='目标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wxauth_router.WechatDomain', verbose_name='公众号域'),
        ),
    ]
