# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0004_merge_20170112_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='wxauth_router.WechatApp', verbose_name='微信APP'),
        ),
        migrations.AlterField(
            model_name='wechatdomain',
            name='app_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='APP_ID'),
        ),
        migrations.AlterField(
            model_name='wechatdomain',
            name='app_secret',
            field=models.CharField(max_length=50, verbose_name='APP_SECRET'),
        ),
    ]
