# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0005_auto_20170205_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='domain',
            field=models.CharField(default=None, help_text='公众号 > 开发 > 接口权限 > 网页授权获取用户基本信息', max_length=100, verbose_name='公众号网页授权域名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='verify_key',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='认证文件编码'),
        ),
    ]
