# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0005_auto_20160525_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='头像文件'),
        ),
    ]
