# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0006_auto_20170205_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatapp',
            name='app_id',
            field=models.CharField(max_length=50, verbose_name='APP_ID'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='domain',
            field=models.CharField(help_text='公众号 > 开发 > 接口权限 > 网页授权获取用户基本信息', max_length=100, verbose_name='公众号网页授权域名'),
        ),
        migrations.AlterField(
            model_name='wechatdomain',
            name='domain',
            field=models.CharField(help_text='公众号 > 开发 > 接口权限 > 网页授权获取用户基本信息', max_length=100, verbose_name='域名'),
        ),
    ]
