# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0006_wechatuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 1, 40, 44, 854639, tzinfo=utc), verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatuser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 1, 40, 50, 110505, tzinfo=utc), verbose_name='更新日期'),
            preserve_default=False,
        ),
    ]
