# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0007_auto_20160919_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechatuser',
            options={'ordering': ['-date_updated', '-pk'], 'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar', verbose_name='头像文件'),
        ),
    ]
