# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0008_auto_20160920_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttarget',
            name='url',
            field=models.URLField(verbose_name='目标URL'),
        ),
    ]
