# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0008_auto_20170205_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatapp',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='API 密钥'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='apiclient_cert',
            field=models.TextField(blank=True, default='', verbose_name='PEM 支付证书'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='apiclient_key',
            field=models.TextField(blank=True, default='', verbose_name='PEM 支付私钥'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='mch_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='商户号 MCH ID'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='notify_url',
            field=models.URLField(blank=True, default='', verbose_name='异步回调URL'),
        ),
    ]
