# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0011_auto_20170205_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='biz_account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='公众平台微信号'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='biz_aes_key',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='公众平台AES密钥'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='biz_origin',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='公众平台原始ID'),
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='biz_token',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='公众平台接口令牌'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='verify_key',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='公众平台认证文件编码'),
        ),
    ]
