# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0012_auto_20170205_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='可以填写公众号的显示名称', max_length=150, verbose_name='标题')),
                ('app_id', models.CharField(max_length=50, unique=True, verbose_name='APP_ID')),
                ('app_secret', models.CharField(max_length=50, verbose_name='APP_SECRET')),
                ('notify_url', models.URLField(blank=True, default='', verbose_name='授权回调地址')),
                ('return_url', models.URLField(blank=True, default='', verbose_name='授权跳转地址')),
                ('mch_id', models.CharField(blank=True, default='', max_length=50, verbose_name='商户号 MCH ID')),
                ('app_gateway', models.CharField(blank=True, default='', help_text='除服务窗外其他的应用，目前未做强制校验，可以不用填写', max_length=150, verbose_name='应用网关')),
                ('rsa2_app_key_public', models.TextField(blank=True, default='', verbose_name='RSA2(SHA256)应用公钥')),
                ('rsa2_app_key_private', models.TextField(blank=True, default='', verbose_name='RSA2(SHA256)应用私钥')),
                ('rsa2_alipay_key_public', models.TextField(blank=True, default='', verbose_name='RSA2(SHA256)支付宝公钥')),
                ('rsa_app_key_public', models.TextField(blank=True, default='', verbose_name='RSA(SHA1)应用公钥')),
                ('rsa_app_key_private', models.TextField(blank=True, default='', verbose_name='RSA(SHA1)应用私钥')),
                ('rsa_alipay_key_public', models.TextField(blank=True, default='', verbose_name='RSA(SHA1)支付宝公钥')),
                ('aes_key', models.CharField(blank=True, default='', max_length=150, verbose_name='接口AES密钥')),
            ],
            options={
                'verbose_name_plural': '支付宝APP',
                'verbose_name': '支付宝APP',
                'db_table': 'wxauth_alipay_app',
            },
        ),
        migrations.AddField(
            model_name='wechatapp',
            name='return_url',
            field=models.URLField(blank=True, default='', verbose_name='授权跳转地址'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='app_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='APP_ID'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='notify_url',
            field=models.URLField(blank=True, default='', verbose_name='授权回调地址'),
        ),
    ]
