# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0013_auto_20170220_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayMapiApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='可以填写公众号的显示名称', max_length=150, verbose_name='标题')),
                ('app_id', models.CharField(max_length=50, unique=True, verbose_name='APP_ID')),
                ('app_secret', models.CharField(blank=True, max_length=50, verbose_name='APP_SECRET')),
                ('notify_url', models.URLField(blank=True, default='', verbose_name='授权回调地址')),
                ('return_url', models.URLField(blank=True, default='', verbose_name='授权跳转地址')),
            ],
            options={
                'verbose_name_plural': '支付宝旧版APP',
                'verbose_name': '支付宝旧版APP',
                'db_table': 'wxauth_alipay_mapi_app',
            },
        ),
        migrations.AlterField(
            model_name='alipayapp',
            name='app_secret',
            field=models.CharField(blank=True, max_length=50, verbose_name='APP_SECRET'),
        ),
        migrations.AlterField(
            model_name='wechatapp',
            name='app_secret',
            field=models.CharField(blank=True, max_length=50, verbose_name='APP_SECRET'),
        ),
    ]
