# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0014_auto_20170228_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaymapiapp',
            name='seller_account_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='卖家支付宝账号别名'),
        ),
        migrations.AddField(
            model_name='alipaymapiapp',
            name='seller_email',
            field=models.CharField(blank=True, help_text='卖家Email或手机号', max_length=255, verbose_name='卖家支付宝用户号'),
        ),
    ]
