# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0020_auto_20170313_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20, verbose_name='币种')),
                ('date', models.DateField(verbose_name='汇率时间')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='汇率（兑1美元）')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
            },
        ),
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together=set([('currency', 'date')]),
        ),
    ]
