# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0023_cmbpayapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wxauth_router.WechatApp', verbose_name='上级'),
        ),
    ]
