# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth_router', '0025_auto_20170504_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatapp',
            name='withdraw_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wxapp', to='wxauth_router.WechatApp', verbose_name='提现关联公众号'),
        ),
    ]
