# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('format', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('json', 'JSON 对象'), ('file', '文件对象'), ('choice_single', '单项选择'), ('choice_multiple', '多项选择')], default='text', max_length=20)),
                ('meta_data', models.TextField(blank=True, default='', help_text='辅助数据')),
            ],
            options={
                'db_table': 'config_option',
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
    ]
