# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='选项标题'),
        ),
        migrations.AlterField(
            model_name='option',
            name='format',
            field=models.CharField(choices=[('text', '文本'), ('number', '数字'), ('json', 'JSON 对象'), ('file', '文件对象'), ('choice_single', '单项选择'), ('choice_multiple', '多项选择')], default='text', max_length=20, verbose_name='选项格式'),
        ),
        migrations.AlterField(
            model_name='option',
            name='meta_data',
            field=models.TextField(blank=True, default='', verbose_name='辅助数据'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='选项关键字'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='选项值'),
        ),
    ]
